
project_id = "rjvpzflhgwduveemjibw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = "enabled"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
port = 54327

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-knowledge-base]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.update-knowledge-base]
verify_jwt = true

[functions.widget]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.admin-login-as-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-user-management]
verify_jwt = true

[functions.admin-system-settings]
verify_jwt = true
