
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://supa.streamifymail.com";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiAiSldUIiwiYWxnIjogIkhTMjU2In0.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzQ5OTY1OTc4LAogICJleHAiOiAxOTA3NjQ1OTc4Cn0.Pq0V4J6w9CDAJauHP93HHnWLec2tAyTLFxwwssMWgDc";

// Stripe configuration
export const STRIPE_PUBLISHABLE_KEY = "pk_test_51RFmDlEJIUEdIR4sedRci768v80RVlKtzRH7kVPIilW6mEQ6rM4r472y805fwLGC7tlntSZf8RpSGWHLLdlMeEPa00IdfdoGv7";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
