// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfuehazuuxymixkzegrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdWVoYXp1dXh5bWl4a3plZ3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTQ3MzEsImV4cCI6MjA2NTM5MDczMX0.Fm9zEAbr1OtvpZ0TubxXOuwVlLQuok81KjnzSR9ytE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);